[project]
name = "ticketing-support-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "load-dotenv>=0.1.0",
    "openai>=1.107.0",
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
]
